base: core18
name: freemind
summary: A premier mind-mapping software written in Java
description: |
  A mind mapper, and at the same time an easy-to-operate hierarchical editor
  with strong emphasis on folding. These two are not really two different
  things, just two different descriptions of a single application. Often used
  for knowledge and content management.

  Homepage: http://freemind.sourceforge.net

confinement: strict
grade: stable
icon: data/gui/freemind.png
adopt-info: freemind

apps:
  freemind:
    command: desktop-launch $SNAP/freemind/freemind.sh
    plugs: 
      - cups-control
      - desktop
      - desktop-legacy
      - home
      - network
      - x11
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $SNAP/usr/lib/jvm/default-java/bin:$SNAP/usr/lib/jvm/default-java/jre/bin:$PATH

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - xdg-user-dirs

  jdk:
    plugin: nil
    stage-packages:
        -  default-jre
    filesets:
        jdk-bits: [-usr/lib/jvm/default-java/bin,
                   -usr/lib/jvm/default-java/include,
                   -usr/lib/jvm/default-java/lib,
                   -usr/share/doc]
    stage:
        - $jdk-bits

  freemind:
    after: [desktop-glib-only, jdk]
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/freemind $SNAPCRAFT_PART_INSTALL/meta/gui
      unzip -o freemind*.zip -d $SNAPCRAFT_PART_INSTALL/freemind
      chmod +x $SNAPCRAFT_PART_INSTALL/freemind/freemind.sh
      cp ./data/gui/* $SNAPCRAFT_PART_INSTALL/meta/gui/
      snapcraftctl set-version "$(ls freemind-*.zip|sed 's/.*-\([^-]\+\).zip/\1/'|tr -s '_' '-')"

    build-packages:
      - default-jre
      - unzip
